### ISSUE TITLE
error while inserting test data in production rds instance

### ISSUE THREAD

**Issue by sid88in** [serverless/serverless-graphql#209]
Unhandled rejection Error: Unable to acquire a connection
    at Client_PG.acquireConnection (/Users/sid.gupta/serverless-graphql/app-backend/rds/node_modules/knex/lib/client.js:346:40)
    at Runner.ensureConnection (/Users/sid.gupta/serverless-graphql/app-backend/rds/node_modules/knex/lib/runner.js:215:24)
    at Runner.run (/Users/sid.gupta/serverless-graphql/app-backend/rds/node_modules/knex/lib/runner.js:47:42)
    at Builder.Target.then (/Users/sid.gupta/serverless-graphql/app-backend/rds/node_modules/knex/lib/interface.js:35:43)
    at Object.<anonymous> (/Users/sid.gupta/serverless-graphql/app-backend/rds/seed-data/seed_prod.js:23:4)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by sid88in** [comment]
after hardcoding url in seed_prod.js the process is stuck at : 

```
23:53:06-sid.gupta@SidG-1081:~/serverless-graphql/app-backend/rds$ yarn deploy-prod
yarn deploy-prod v1.0.1
$ env-cmd ../../config/security.env.prod yarn migrate --env production && yarn seed-prod && env-cmd ../../config/security.env.prod serverless --stage=production deploy
Using environment: production
Already up to date
null
```

**Comment by sid88in** [comment]
https://github.com/serverless/serverless-graphql/pull/213 fixes this
