### ISSUE TITLE
playground - production message: "Internal server error"

### ISSUE THREAD

**Issue by sid88in** [serverless/serverless-graphql#216]

**Comment by sid88in** [comment]
```
2017-12-23T09:11:44.927Z	4a58620f-e7c1-11e7-a6db-f52111b67e20	Knex: run
$ npm install sqlite3 --save
Error: Cannot find module 'sqlite3'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Client_SQLite3._driver (/var/task/node_modules/knex/lib/dialects/sqlite3/index.js:79:12)
at Client_SQLite3.initializeDriver (/var/task/node_modules/knex/lib/client.js:249:26)
at Client_SQLite3.Client (/var/task/node_modules/knex/lib/client.js:126:10)
at new Client_SQLite3 (/var/task/node_modules/knex/lib/dialects/sqlite3/index.js:62:20)
at Knex (/var/task/node_modules/knex/lib/index.js:60:34)
at Object.<anonymous> (/var/task/handler.js:195:37)
at __webpack_require__ (/var/task/handler.js:20:30)
at Object.<anonymous> (/var/task/handler.js:93:18)
at __webpack_require__ (/var/task/handler.js:20:30)
at /var/task/handler.js:63:18
at Object.<anonymous> (/var/task/handler.js:66:10)
at Module._compile (module.js:570:32)
```

**Comment by sid88in** [comment]
@pradel can you please look into this? The problem seems to be coming from knexfile configs. In production, even though sqlite is not required, knex tries to find it because of config in development environment?

**Comment by nickdecooman** [comment]
The issue also seems to occur for dynamodb in production

**Comment by sid88in** [comment]
hey @nickdecooman .. we are aware of the issue (started happening 2 days ago) and have prioritized to debug/fix this. 

Any help is appreciated :) 

thanks
Sid

**Comment by sid88in** [comment]
@nickdecooman another thing I noticed is that /graphql endpoint works under the hood (you can test it via postman).. but some problem with /playground endpoint

**Comment by sid88in** [comment]
graphiQL is working fine - tested by @JstnEdr

**Comment by kkarimi** [comment]
Can confirm graphiQL is fine with dynamodb in prod but only when there is a query present, with an empty query on load it also returns `{
  "message": "Internal server error"
}`

**Comment by sid88in** [comment]
good catch @kkarimi I'll create an issue to test edge cases in all integrations! We do need more testing ;)

**Comment by sid88in** [comment]
https://github.com/graphcool/graphql-playground/issues/342

**Comment by sid88in** [comment]
https://github.com/serverless/serverless-graphql/pull/267
