### ISSUE TITLE
RDS Production Errors

### ISSUE THREAD

**Issue by sid88in** [serverless/serverless-graphql#257]
```2018-01-08T13:34:42.644Z	aedb25e9-f478-11e7-bbff-4734590d8fbd	{ Error: connect ETIMEDOUT
at Connection._handleConnectTimeout (/var/task/node_modules/mysql/lib/Connection.js:419:13)
at Socket.g (events.js:292:16)
at emitNone (events.js:86:13)
at Socket.emit (events.js:185:7)
at Socket._onTimeout (net.js:338:8)
at ontimeout (timers.js:386:14)
at tryOnTimeout (timers.js:250:5)
at Timer.listOnTimeout (timers.js:214:5)
--------------------
at Protocol._enqueue (/var/task/node_modules/mysql/lib/protocol/Protocol.js:145:48)
at Protocol.handshake (/var/task/node_modules/mysql/lib/protocol/Protocol.js:52:23)
at Connection.connect (/var/task/node_modules/mysql/lib/Connection.js:130:18)
at /var/task/node_modules/knex/lib/dialects/mysql/index.js:106:18
at Promise._execute (/var/task/node_modules/bluebird/js/release/debuggability.js:303:9)
at Promise._resolveFromExecutor (/var/task/node_modules/bluebird/js/release/promise.js:483:18)
at new Promise (/var/task/node_modules/bluebird/js/release/promise.js:79:10)
at Client_MySQL.acquireRawConnection (/var/task/node_modules/knex/lib/dialects/mysql/index.js:104:12)
at Object.create (/var/task/node_modules/knex/lib/client.js:283:25)
at Pool._createResource (/var/task/node_modules/generic-pool/lib/Pool.js:304:42)
at Pool._ensureMinimum (/var/task/node_modules/generic-pool/lib/Pool.js:334:12)
at Pool.start (/var/task/node_modules/generic-pool/lib/Pool.js:408:10)
at new Pool (/var/task/node_modules/generic-pool/lib/Pool.js:127:12)
at Object.createPool (/var/task/node_modules/generic-pool/index.js:11:12)
at Client_MySQL.initializePool (/var/task/node_modules/knex/lib/client.js:336:29)
at Client_MySQL.Client (/var/task/node_modules/knex/lib/client.js:129:12)
originalMessage: 'select * from `users` where `screen_name` = \'LeoDiCaprio\' - connect ETIMEDOUT',
message: 'Error in resolver Query.getTwitterFeed\nselect * from `users` where `screen_name` = \'LeoDiCaprio\' - connect ETIMEDOUT' }```

**Comment by sid88in** [comment]
Might be happening because of : 

```    client: process.env.DATABASE_TYPE === 'pg' ? 'pg' : 'mysql',
```

when we hardcode this to 'pg' I don't get 500

**Comment by sid88in** [comment]
Another error while deploying:

```
19:30:04-sid.gupta@SidG-1081:~/serverless-graphql/app-backend/rds$ yarn deploy-prod
yarn deploy-prod v1.0.1
$ env-cmd ../../config/security.env.prod yarn migrate --env production && env-cmd ../../config/security.env.prod yarn seed-prod && env-cmd ../../config/security.env.prod serverless --stage=production deploy
Using environment: production
TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at /Users/sid.gupta/serverless-graphql/app-backend/rds/node_modules/knex/lib/client.js:351:13
    at tryCatcher (/Users/sid.gupta/serverless-graphql/app-backend/rds/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/sid.gupta/serverless-graphql/app-backend/rds/node_modules/bluebird/js/release/catch_filter.js:17:41
    at tryCatcher (/Users/sid.gupta/serverless-graphql/app-backend/rds/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/sid.gupta/serverless-graphql/app-backend/rds/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/sid.gupta/serverless-graphql/app-backend/rds/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/sid.gupta/serverless-graphql/app-backend/rds/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/sid.gupta/serverless-graphql/app-backend/rds/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/sid.gupta/serverless-graphql/app-backend/rds/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/sid.gupta/serverless-graphql/app-backend/rds/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/sid.gupta/serverless-graphql/app-backend/rds/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Comment by justinram22** [comment]
Just ran into this issue myself -- did you by chance end up keeping the double quotes in your config file? Once I removed the double quotes it worked correctly:

`DATABASE_TYPE=pg`

(And same goes for DATABASE_URL)

**Comment by sid88in** [comment]
@justinram22 interesting. Have to check again, but the above errors were intermediate.
