### ISSUE TITLE
Got error when run yarn install

### ISSUE THREAD

**Issue by thanhpd-teko** [serverless/serverless-graphql#377]
Hi,
Steps:
- Clone project
- Cd into \app-backend\appsync\dynamo
- Run yarn install
I got the error below:

[!] (uglify plugin) Error: Error transforming bundle with 'uglify' plugin: `warnings` is not a supported option
Error: Error transforming bundle with 'uglify' plugin: `warnings` is not a supported option
    at error (C:\Users\Teko\AppData\Local\Yarn\Cache\v4\.tmp\06089c6876814e6693e0ee24b9919dae.daaa07a9705b8a4669acd5f98a599ab443cb31d6.prepare\node_modules\rollup\dist\rollup
.js:185:14)
    at Promise.resolve.then.then.catch.err (C:\Users\Teko\AppData\Local\Yarn\Cache\v4\.tmp\06089c6876814e6693e0ee24b9919dae.daaa07a9705b8a4669acd5f98a599ab443cb31d6.prepare\n
ode_modules\rollup\dist\rollup.js:17618:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

Help me please!

**Comment by mohamedGamalAbuGalala** [comment]
Same error here, any updates :thinking:

**Comment by oznekenzo** [comment]
Ive gotten this as well

**Comment by oznekenzo** [comment]
@mohamedGamalAbuGalala @thanhpd-teko 
Delete your node_modules folder and delete your yarn-lock files - worked for me
